### ISSUE TITLE
Welcome Image

### ISSUE THREAD

**Issue by NeroxR6S** [CTK-WARRIOR/Discord-Bot-For-Starters#1]
I cannot put the "attachment" in an embed by doing .setImage(attachment) Please help me

**Comment by LegendaryEmoji** [comment]
.setImage() is not accepting attachment as data, only url

more info - [click me](https://discord.js.org/#/docs/main/stable/class/MessageEmbed?scrollTo=setImage)

**Comment by Yonle** [comment]
You can't do it with `MessageAttachment`.

**Comment by Yonle** [comment]
@CTK-WARRIOR .

**Comment by Yonle** [comment]
Issue closed due to inactivity.
