### ISSUE TITLE
Ban and Kick is not working

### ISSUE THREAD

**Issue by MeetThumar888** [CTK-WARRIOR/Discord-Bot-For-Starters#3]
Please check code of ban and kick because its not working.

**Comment by mxyz-org** [comment]
const discord = require("discord.js");

module.exports = {
  name: "ban",
  category: "moderation",
  description: "Ban anyone with one shot whithout knowing anyone xD",
  usage: "ban <@user> <reason>",
  cooldown: 50000,
  botPermission: ["BAN_MEMBERS"],
  authorPermission: ["BAN_MEMBERS"],
  run: async (client, message, args) => {
    
    if(!message.member.hasPermission("BAN_MEMBERS")) {
      return message.channel.send(`**${message.author.username}**, You do not have perms to ban someone`)
    }
    
    if(!message.guild.me.hasPermission("BAN_MEMBERS")) {
      return message.channel.send(`**${message.author.username}**, I do not have perms to ban someone`)
    }
    
    const target = message.mentions.members.first();
    
    if(!target) {
      return message.channel.send(`**${message.author.username}**, Please mention the person who you want to ban.`)
    }
    
    if(target.id === message.author.id) {
      return message.channel.send(`**${message.author.username}**, You can not ban yourself!`)
    }
    
   
    
   if(!args[1]) {
     return message.channel.send(`**${message.author.username}**, Please Give Reason To ban Member`)
   }
                  let channel = db.fetch(`modlog_${message.guild.id}`)
            if (channel == null) return;
            if (!channel) return;
    let embed2 = new discord.MessageEmbed()
    .setTitle("Action : Ban")
    .setDescription(`Banned ${target} (${target.id})`)
    .setColor("#ff2050")
    .setThumbnail(target.avatarURL)
    message.channel.send(embed2)
      if (target) {
      const targetMember = message.guild.members.cache.get(target.id)
      targetMember.ban()
    
      }
  }
}
fixed*

**Comment by Yonle** [comment]
Are you sure the code is not working? Please put error code in codeblock and send it there.

**Comment by CipherHYT** [comment]
@MeetThumar888 please put the error code so we can fix the problem for you.

**Comment by Yonle** [comment]
Remember: We can't see your  computer / your device screen, and we can't login on it. So that's why you need give us a error.

Saying `it's not working` without any error just makes us confuse alot.

**Comment by Yonle** [comment]
@CTK-WARRIOR I guess we can close this issue.

**Comment by Yonle** [comment]
Issue closed due to inactivity.
