### ISSUE TITLE
imdb command not working

### ISSUE THREAD

**Issue by kris10kyss** [CTK-WARRIOR/Discord-Bot-For-Starters#7]
imdb command is always unable to find anything about a movie title

**Comment by LegendaryEmoji** [comment]
typo in imdb cmd
line [#26](https://github.com/CTK-WARRIOR/Discord-Bot-For-Starters/blob/main/commands/info/imdb.js#L26)
`Responce` => `Response`
it should fix your problem

**Comment by CTK-WARRIOR** [comment]
Fixed the issue :D

**Comment by LegendaryEmoji** [comment]
thonk u

**Comment by CTK-WARRIOR** [comment]
np
